import { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { getOwner } from "@/lib/getOwner";
import Header from "./header";

const fontSans = Inter({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const name = await getOwner();

	return (
		<html lang="en">
			<body className={`p-5 ${fontSans.className} antialiased`}>
				<Header />
				{children}
				<footer className="mt-4 border-t border-white">
					<p className="text-sm text-gray-500">
						© 2023 {name}. All rights reserved.
					</p>
				</footer>
			</body>
		</html>
	);
}
