import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="p-4 w-full h-full">
				<h3 className="text-2xl font-bold mb-4">Next.js App Layout</h3>
				{children}
			</body>
		</html>
	);
}
